#!/bin/bash
#SBATCH --job-name=vad_lstm
#SBATCH --partition=2080ti
#SBATCH --gres=gpu:1
#SBATCH --output=vad_lstm
#SBATCH --cpus-per-task=4
module add cuda/10.1
conda activate ywg
python main.py --stage 1 --lr 0.0005
